# syntax=docker/dockerfile:1
FROM gcc:latest
WORKDIR /code

# dependancies and libraries requirements
RUN apt-get update
#RUN apt-get install build-essential
# RUN apt-get install --no-install-recommends -y gcc

# DEBUG redirect stdout and stderr to files
# RUN exec >/code/stdout.log
# RUN exec 2>/code/stderr.log
